### PR TITLE
Support babel's resolveModuleSource custom resolvers

### PR DESCRIPTION
**Pull request by real34**
Here is my attempt at #5

### CODE REVIEW

**Comment by detrohutt** [comment]
Thanks for the PR! I made some adjustments. If those work for you I'll go ahead and merge this. :)

**Comment by detrohutt** [comment]
@real34 Whoops, I committed too soon! Don't pull it if you haven't yet. I'm going to amend the commit with some needed changes in a few minutes!

**Comment by detrohutt** [comment]
Ok *now* it should be good. Let me know if that works for you.

**Comment by real34** [comment]
It looks much more cleaner indeed! It works fine for me, thank you very much work your help.

**Comment by detrohutt** [comment]
I went ahead and published this(2.0.1-rc.0) so you can go ahead and start using it. Over the next few days I'm going to get the tests, dependencies, and a few other things in order and then do a proper release. Thanks again @real34 for all your help with this release!

**Comment by real34** [comment]
Awesome! Thank you.

**Pull request merged**
