### PR TITLE
add in variableDeclarator to handle require statements

### PR DESCRIPTION
**Pull request by rphuber**

### CODE REVIEW

**Comment by rphuber** [comment]
adding in some logic to also handle the use case for using require statements (commonjs).  Great plugin!

**Comment by rphuber** [comment]
Closing for now because I think the output ast is wrong.

**Comment by detrohutt** [comment]
Alright. If you can, amend that commit to take out the changes to package-lock.json. Not sure why it's being changed in the first place.. I recently added an `update-lock-files.sh` file that runs on commit but it's only supposed to run if `package.json` changes. If you just ran `npm install` it should have just used the versions in the current lock files as far as I know. If you can't get those changes to revert, let me know.

**Comment by detrohutt** [comment]
@rphuber I just deprecated this package today, renaming it to `babel-plugin-import-graphql` (see the README). If you still want to do this PR, please PR against [the new repo](https://github.com/detrohutt/babel-plugin-import-graphql). None of the source files have changed so you should be able to switch over pretty easily.

**Comment by rphuber** [comment]
Will do.  I'll try to get this done this weekend.  I'll remove the package.lock stuff too.

**Pull request closed without merging**
